language: node_js

node_js:
  - 9
  - 8
  - 7

os:
  - osx

script:
  - npm run test

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npm run travis-deploy-once "npm run semantic-release"
