language: node_js

node_js:
  - 9
  - 8
  - 7


addons:
  ssh_known_hosts: github.com

script:
  - npm run test

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx travis-deploy-once "npx semantic-release"
